import streamlit as st
import json
import pandas as pd
from datetime import datetime
import os

st.set_page_config(page_title="Agentic AI Interview")

st.title("AI in je bedrijf – Agentic SME Interview")
st.caption("This conversational AI interviewer assesses AI adoption, productivity, barriers, and digital autonomy. All responses are anonymous.")

# ----- Pre‑scripted interview flow (no API) -----
# Each step has the assistant's question and the key the user's answer will be stored under.
SCRIPT = [
    {"question": "Hello! I'm an AI interviewer for the 'AI in je bedrijf' initiative. This interview will take about 10 minutes and is completely anonymous. May I ask for your consent to continue?", "key": None},
    {"question": "Thank you. To start, what sector does your company operate in?", "key": "sector"},
    {"question": "How many employees work in your company?", "key": "employees"},
    {"question": "How many years has the company been in business?", "key": "years_in_business"},
    {"question": "What digital tools or AI‑based systems do you currently use? (For example, inventory management, chatbots, predictive maintenance)", "key": "tools"},
    {"question": "You mentioned some tools. Overall, by what percentage would you estimate your productivity has improved since adopting these tools? If you’re unsure, feel free to give a rough range.", "key": "productivity_improvement_percent"},
    {"question": "What are the main barriers that prevent you from adopting more AI? (e.g., cost, skills, data quality, trust, integration, regulation, vendor lock‑in)", "key": "barriers"},
    {"question": "Who owns the data generated by your AI/digital tools? Could you easily switch vendors if you wanted to?", "key": "autonomy_owner"},
    {"question": "On a scale from 1 to 5, how in control do you feel over the AI tools you use? (1 = no control, 5 = full control)", "key": "digital_autonomy_score"},
    {"question": "Thank you. Based on our conversation, here is a summary:\n- Adoption level: medium\n- Productivity gain: as reported\n- Autonomy: as reported\n\nThank you for your time. Your completion code is: AI-SME-2026", "key": None, "is_end": True},
]

if "step" not in st.session_state:
    st.session_state.step = 0
    st.session_state.answers = {}
    st.session_state.messages = []

# Sidebar option to append demo data
append_demo = st.sidebar.checkbox(
    "Append my response to the demo dataset after completion",
    value=False,
    help="Your anonymised answers will be added to the synthetic dataset for dashboard analysis."
)

# Display conversation so far
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Show next question if interview not finished
if st.session_state.step < len(SCRIPT):
    current = SCRIPT[st.session_state.step]
    # If assistant hasn't spoken yet in this step, speak now
    if len(st.session_state.messages) == st.session_state.step * 2:
        with st.chat_message("assistant"):
            st.markdown(current["question"])
        st.session_state.messages.append({"role": "assistant", "content": current["question"]})
    # Get user input
    user_input = st.chat_input("Type your answer here...")
    if user_input:
        st.session_state.messages.append({"role": "user", "content": user_input})
        # Save answer if this step has a key
        if current["key"] is not None:
            st.session_state.answers[current["key"]] = user_input
        st.session_state.step += 1
        st.rerun()
else:
    st.info("Interview complete. Thank you for your time.")
    # If append_demo is checked, extract structured data
    if append_demo and st.session_state.answers:
        try:
            # Map free-text answers to the required data format
            sector = st.session_state.answers.get("sector", "Unknown")
            employees_raw = st.session_state.answers.get("employees", "0")
            employees = int(''.join(filter(str.isdigit, employees_raw))) if any(c.isdigit() for c in employees_raw) else None
            years_raw = st.session_state.answers.get("years_in_business", "0")
            years = int(''.join(filter(str.isdigit, years_raw))) if any(c.isdigit() for c in years_raw) else None
            prod_raw = st.session_state.answers.get("productivity_improvement_percent", "0")
            productivity = float(''.join(filter(lambda c: c.isdigit() or c=='.', prod_raw))) if any(c.isdigit() for c in prod_raw) else None
            barriers_raw = st.session_state.answers.get("barriers", "").lower()
            possible_barriers = ["skills","cost","data quality","trust","integration","regulation","vendor lock‑in"]
            detected_barriers = [b for b in possible_barriers if b in barriers_raw]
            autonomy_score_raw = st.session_state.answers.get("digital_autonomy_score", "3")
            autonomy_score = float(''.join(filter(lambda c: c.isdigit() or c=='.', autonomy_score_raw))) if any(c.isdigit() for c in autonomy_score_raw) else 3.0
            adoption_level = "medium"  # hardcoded demo
            data = {
                "sector": sector,
                "employees": employees,
                "years_in_business": years,
                "ai_adoption_level": adoption_level,
                "productivity_improvement_percent": productivity,
                "main_barriers": "; ".join(detected_barriers) if detected_barriers else "cost",
                "digital_autonomy_score": autonomy_score,
                "vendor_lock_in_concern": "neutral",
                "prolific_pid": "demo_" + datetime.now().strftime("%Y%m%d%H%M%S"),
                "completed": True
            }
            df_new = pd.DataFrame([data])
            csv_path = "data/responses_demo.csv"
            if os.path.exists(csv_path):
                df_new.to_csv(csv_path, mode="a", index=False, header=False)
            else:
                df_new.to_csv(csv_path, index=False)
            st.success("Your anonymised response has been added. Visit the Dashboard to see the update.")
        except Exception as e:
            st.warning(f"Could not save data: {e}")
